#lane_control/lane_controller_node

## ADD CONFIGS HERE

v: 0.2
v_min: 0.15
L_d: 0.2
L_max: 0.3
k: 0.3 # default: L/2v                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
d_offset: 0.0 
omega_ff: 0
