#lane_control/lane_controller_node

## ADD CONFIGS HERE

v: 0.2
L_d: 0.25
k: 0.4   # default: 0.5                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
d_offset: 0.0 
omega_ff: 0