# path to model is by default relative to the package

model_file: "/include/object_detection/weights/sim.pt"
config_file: "/config/object_detection_node/sim_config.yaml"
# model_file: "/include/object_detection/weights/real.pt"
# config_file: "/config/object_detection_node/real_config.yaml"
safe_distance: 0.2